# Generated by Django 3.0.5 on 2020-07-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=128)),
                ('page_title', models.CharField(blank=True, max_length=128, null=True)),
                ('friendly_link', models.CharField(blank=True, max_length=128, null=True)),
                ('page_types', models.CharField(choices=[('home', 'hompage'), ('me', 'about me')], default='home', max_length=64)),
                ('post_data', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PagesSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('main_text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
            ],
        ),
        migrations.CreateModel(
            name='MenuTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_external_link', models.BooleanField(default=False)),
                ('external_link', models.CharField(blank=True, max_length=128, null=True)),
                ('display', models.BooleanField(default=True)),
                ('font_awesome_icon', models.CharField(blank=True, max_length=128, null=True)),
                ('show_icon_only', models.BooleanField(default=False)),
                ('is_a_logo', models.BooleanField(default=False)),
                ('image_for_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('to_new_tab', models.BooleanField(default=False)),
                ('priority', models.DecimalField(decimal_places=0, default=0, max_digits=9999999)),
                ('is_submenu', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.MenuTab')),
            ],
        ),
    ]
