# Generated by Django 3.0.5 on 2020-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_types',
            field=models.CharField(choices=[('home', 'hompage'), ('me', 'about me'), ('contact', 'contact')], default='home', max_length=64),
        ),
    ]
