# Generated by Django 3.0.5 on 2020-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200722_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagessetting',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_types',
            field=models.CharField(choices=[('home', 'hompage'), ('me', 'about me'), ('contact', 'contact'), ('portfolio', 'portfolio')], default='home', max_length=64),
        ),
    ]
