"""
Django settings for agatka project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+-c!ht^y5a#uvt)9t#-1ppjjsie6mq(5zwh&2ygrlajq2yuk5y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'pages',
    'homepage',
    'about_me',
    'contact',
    'images',
    'portfolio',
    'better_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agatka.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "static_dirs/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agatka.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

static_str = "static_dirs/static"
STATIC_URL = f'/{static_str}/'
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(PROJECT_DIR, static_str)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, static_str),
]

media_str = "static_dirs/media"
MEDIA_URL = f'/{media_str}/'
MEDIA_ROOT  = os.path.join(BASE_DIR, media_str)

RECAPTCHA_PUBLIC_KEY = '6Lekl7wZAAAAANsc8z8k-BAH6OupRViLC7T3VH-0'
RECAPTCHA_PRIVATE_KEY = '6Lekl7wZAAAAANcMq_ZVIjFddHctMKxEyCFFOTLw'
RECAPTCHA_REQUIRED_SCORE = 0.85

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # new
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "noreply.chopchu.web@gmail.com"
EMAIL_HOST_PASSWORD = 'Kotlet1233'
EMAIL_PORT = 587
EMAIL_USE_TLS = True


"""
static_str = "static_dirs/static"
STATIC_URL = f'/{static_str}/'
if DEBUG: 
   STATIC_ROOT = os.path.join(BASE_DIR, '/{static_str}')
else:
   STATIC_ROOT = os.path.join(BASE_DIR, static_str) 

media_str = "static_dirs/media"
MEDIA_URL = f'/{media_str}/'
if DEBUG: 
   MEDIA_ROOT = os.path.join(BASE_DIR, '/{media_str}')
else:
   MEDIA_ROOT = os.path.join(BASE_DIR, media_str)


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static_dirs"),
]
"""

"""
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER ='noreply.chopchu.web@gmail.com'
EMAIL_HOST ='smtp.gmail.com'
EMAIL_PORT =587
EMAIL_USE_TLS =True
EMAIL_HOST_PASSWORD ='Kotlet1233'
"""