# Generated by Django 3.0.5 on 2020-08-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mails',
        ),
    ]
