# Generated by Django 3.0.5 on 2020-07-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.TextField(blank=True, null=True)),
                ('font_awesome_icon', models.CharField(blank=True, max_length=128, null=True)),
                ('to_new_tab', models.BooleanField(default=False)),
                ('show_icon_only', models.BooleanField(default=False)),
            ],
        ),
    ]
