# Generated by Django 3.0.5 on 2020-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutabs',
            name='priority',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9999999),
        ),
    ]
