# Generated by Django 3.0.5 on 2020-07-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_menutabs_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuTabs',
            new_name='MenuTab',
        ),
    ]
