# Generated by Django 3.0.5 on 2020-07-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200722_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutab',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menutab',
            name='image_for_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='menutab',
            name='is_a_logo',
            field=models.BooleanField(default=False),
        ),
    ]
