# Generated by Django 3.0.5 on 2020-07-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200722_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=128)),
                ('friendly_link', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='menutab',
            name='is_submenu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menutab',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.MenuTab'),
        ),
    ]
