# Generated by Django 3.0.5 on 2020-07-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200722_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutab',
            name='link',
        ),
        migrations.AddField(
            model_name='menutab',
            name='external_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='menutab',
            name='is_external_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menutab',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_types',
            field=models.CharField(choices=[('home', 'hompage')], default='green', max_length=64),
        ),
        migrations.AddField(
            model_name='page',
            name='post_data',
            field=models.CharField(default=True, max_length=128),
            preserve_default=False,
        ),
    ]
