# Generated by Django 3.0.5 on 2020-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200722_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='friendly_link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='post_data',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
