# Generated by Django 3.0.5 on 2020-07-22 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200722_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(blank=True, max_length=128, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Page')),
            ],
        ),
    ]
