# Generated by Django 3.0.5 on 2020-07-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_pagessetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagessetting',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
