# Generated by Django 3.0.5 on 2020-07-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200722_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id_name',
            field=models.CharField(default='xd', max_length=128),
        ),
    ]
