# Generated by Django 3.0.5 on 2020-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20200722_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagessetting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='pagessetting',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_types',
            field=models.CharField(choices=[('home', 'hompage'), ('me', 'about me')], default='home', max_length=64),
        ),
    ]
