# Generated by Django 3.0.5 on 2020-07-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20200722_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagessetting',
            name='page',
        ),
        migrations.DeleteModel(
            name='MenuTab',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PagesSetting',
        ),
    ]
