# Generated by Django 3.0.5 on 2020-07-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200726_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='relase_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='relase_date',
            field=models.DateTimeField(),
        ),
    ]
