# Generated by Django 3.0.5 on 2020-08-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200726_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_link',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='background_image',
            field=models.ImageField(upload_to='pics/images'),
        ),
    ]
