# Generated by Django 3.0.5 on 2020-08-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200810_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='background_image',
            field=models.FileField(upload_to='pics/images'),
        ),
    ]
