# Generated by Django 3.0.5 on 2020-08-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200810_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='pics/images'),
        ),
    ]
