# Generated by Django 3.0.5 on 2020-08-12 15:53

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20200812_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/images', verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='group',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to=images.models.get_upload_path_for_group, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=images.models.get_upload_path_for_image, verbose_name='image'),
        ),
    ]
