# Generated by Django 3.0.5 on 2020-08-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20200822_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='reducted_image',
        ),
        migrations.RemoveField(
            model_name='group',
            name='reducted_image',
        ),
    ]
