# Generated by Django 3.0.5 on 2020-08-22 12:16

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20200822_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='reducted_image',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.get_upload_path_for_group_reduced_image, verbose_name='reducted_image'),
        ),
    ]
